### ISSUE TITLE
Trouble with workflows in Galaxy

### ISSUE THREAD

**Issue by hdashnow** [Arkarachai/STR-FM#18]
Hi @Arkarachai,

I'm having trouble using the STR-FM workflows in Galaxy. I followed the Galaxy install instructions, and all appeared to work. The STR-FM tools appear in the menu.

When I tried to install the workflow "microsatellite_profiling"  I get the following error message:

Workflow microsatellite_profiling imported successfully. The following tools required by this workflow are missing from this Galaxy instance: name: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/PEsortedSAM2readprofile/1.0.0, id: Combine mapped flaked basesname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/microsatcompat/1.0.0, id: Check microsatellites motif compatibilityname: toolshed.g2.bx.psu.edu/repos/devteam/join/gops_join_1/1.0.0, id: Joinname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/microsatpurity/1.0.0, id: Select uninterrupted microsatellitesname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/GenotypeSTR/2.0.0, id: Correct genotype for microsatellite errorsname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/microsatellite/1.0.0, id: Microsatellite detectionname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/fetchflank/1.0.0, id: Fetch flanking basesname: toolshed.g2.bx.psu.edu/repos/arkarachai-fungtammasan/microsatellite_ngs/space2underscore_readname/1.0.0, id: Read name modifier.

Can you suggest what might be going wrong?

I'm using a freshly installed Galaxy on the [GVL](https://genome.edu.au/) version 3.04
You can access it here: http://130.56.249.152/galaxy
Feel free to make an account and poke around. I'm happy to give you admin to the instance if that would help.

Warm regards,
Harriet

**Comment by Arkarachai** [comment]
Hi Harriet,

Thank you for your interest to use our pipeline. I would be more than happy to address your questions. 

I believe that it's the order of installation. Do you mean that all ~9-11 tools are on STR-FM panel before you import the workflow? If so, it should work.
Also, did you install them from suite_str_fm_1_0 or str_fm? I recommend the former as it contain all dependency tools for the workflow.
Finally, do you plan to run this in command line or in Galaxy? If you plan to do it in command line, it would be better to just install Galaxy and use the command line sample that I have in this site to build your shell script. Although the tools in both command line and Galaxy approach are the same, the workflow and sample shell script were created separately. In short, you don't have to worry about Galaxy workflow if you plan to run it in command line anyway. You just need to install Galaxy in order to use some tools that I borrow from Galaxy
Let me know and we will go from there.
Best,
Chai

P.S. I would like to point out that we have the Galaxy Biostar webboard. 
https://biostar.usegalaxy.org/
If you plan to use it on Galaxy, there are lots of expert there that can help you with similar questions. I got lots of help there as well.

**Comment by hdashnow** [comment]
Hi Chai,

Thanks for responding so quickly. I had installed the tools before importing the workflow. I've checked that I can access the tools individually, and then re-imported the workflow with the same error message.

I'm actually trying to determine how easy this tool is for others to use, so I would like to make sure I can run it in both Galaxy and the command line.

Do you have any suggestions as to why the workflow might not be able to detect the tools? I noticed, that it is only the str_fm tools that are causing errors, not the other dependancies installed in the suite_str_fm. 

Warm regards,
Harriet

**Comment by Arkarachai** [comment]
Hi Harriet,

I see. Let me get in touch with Galaxy team and I will get back to you shortly. 

Best,
Chai

**Comment by Arkarachai** [comment]
Hi Harriet,
Just want to verify. You mean that you finish whole installation including step 3.5, and then you get error message that the tools in workflow cannot be found, right?

Meanwhile, can you try the other repository call "suite_microsatellite_ngs_1_0". It's the original version before we change the name to STR-FM. All the procedure is the same except that you need to change repository name from "suite_str_fm_1_0" to "suite_microsatellite_ngs_1_0" and from "str_fm" to "microsatellite_ngs". If this one work, I think there might be some incorrect link in new repository. If it doesn't, umm I don't know at this point. I might miss one step in the instruction.

**Comment by Arkarachai** [comment]
Dear Harriet,
I post it on Galaxy Biostar and you can find it here.
I register to your galaxy instance using E-mail arkarachai.af@gmail. If you make me temporary admin, I might be able to figure out faster. 
Thanks,
Chai

**Comment by Arkarachai** [comment]
https://biostar.usegalaxy.org/p/13764/

**Comment by hdashnow** [comment]
Hi Chai,

Awesome, thanks for taking a look. I've made you admin on my Galaxy.

Warm regards,
Harriet

**Comment by Arkarachai** [comment]
Dear Harriet,
Would you mind check my admin status again? I log in today and I can't find the admin tab. Probably, the E-mail that I gave you last time has missing ".com". The full E-mail is "arkarachai.af@gmail.com"
Thanks,
Chai

**Comment by hdashnow** [comment]
Ah, yes you're right. Fixed.

**Comment by Arkarachai** [comment]
I will get back to you around this Thursday. The person who help me put this on is out of town until then.

**Comment by hdashnow** [comment]
Brilliant, thanks for you help!

On Mon, Aug 17, 2015 at 12:33 PM, Arkarachai Fungtammasan <
notifications@github.com> wrote:

> I will get back to you around this Thursday. The person who help me put
> this on is out of town until then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Arkarachai/STR-FM/issues/18#issuecomment-131660505.

## 

Harriet Dashnow
President, COMBINE http://combine.org.au/
BSc, BA, MSc (Bioinformatics), PhD candidate
www.harrietdashnow.com

**Comment by Arkarachai** [comment]
Hi Harriet,
We figured out what happen. There are two issues here.
1 It's the problem from my end. Last time that I update the repository, I didn't update link inside the workflow, so the workflow try to find the old version of tools. I will work on this and get back to you around early next week.
2 The Galaxy version that you have bug in workflow configuration. If you can let me know what Galaxy version that you use, I can get in touch with Galaxy admin team to find the way to get around it. It's not crucial just to run STR-FM workflow but it could be problematic later on if you try to view workflow from toolshed.
Thanks,
Chai

**Comment by hdashnow** [comment]
Hi Chai,

Great! What's the next step?

I've had a little trouble figuring out what version of Galaxy I'm running. I'm pretty sure it originates with this commit: https://bitbucket.org/gvl/galaxy-dist-gvl/commits/df5c018f72a4f755c02d9febf04ecf804700ce4f

The date on it is 2014-11-06, if that helps. Is there a file somewhere in the Galaxy code perhaps with the version number in it? 

Warm regards,
Harriet

**Comment by Arkarachai** [comment]
Hi Harriet,

I will forward your message to Galaxy team regarding your Galaxy version. They will get back shortly.
About the STR-FM, please wait few days. I updated the link yesterday, but I want to make sure that someone besides me install this new version. I promise it will be fixed not more than next Tuesday. 

Best,
Chai

**Comment by hdashnow** [comment]
Thanks for all your help! Let me know when I should try it again.

On Fri, Aug 21, 2015 at 11:57 PM, Arkarachai Fungtammasan <
notifications@github.com> wrote:

> Hi Harriet,
> 
> I will forward your message to Galaxy team regarding your Galaxy version.
> They will get back shortly.
> About the STR-FM, please wait few days. I updated the link yesterday, but
> I want to make sure that someone besides me install this new version. I
> promise it will be fixed not more than next Tuesday.
> 
> Best,
> Chai
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Arkarachai/STR-FM/issues/18#issuecomment-133433090.

## 

Harriet Dashnow
President, COMBINE http://combine.org.au/
BSc, BA, MSc (Bioinformatics), PhD candidate
www.harrietdashnow.com

**Comment by Arkarachai** [comment]
Dear Harriet,

It's done. In fact, I took liberty to remove the old version and install a new one for you to prevent confusion with multiple version. If you want, you may try to install yourself. 
You may also notice that there are now v2 for microsatellite profiling. If you gonna use STR in genome from our tools as anchor for STR profiling from short read, I recommend this version. The difference is subtle. In theory, v2 has negligible higher stringency of flanking region to match reference genome. This v2 is also more comparable to the command line. 
It's strange though that I can't specify tools to go to new folder. I can do this in my Galaxy, but I can't even do it myself in your galaxy instant. It doesn't affect your usage though. If this issue bother you, you may consult Galaxy team in biostar.
I hope you enjoy using it. I recommend you start with "TR profiling genome pipeline". Maybe, small reference chromosome with not too small STR length (otherwise there will be too many of them).  Let me know if you have any questions.
As for the Galaxy version, I think it should be fine. It's just a minor bug and it doesn't seem to affect usage.

Best,
Chai

P.S. You may remove me from the admin role.
