### ISSUE TITLE
STR-FM for autopolyploid species

### ISSUE THREAD

**Issue by DenisGoryunov** [Arkarachai/STR-FM#25]
Hi!
May i apply STR-FM for SSR genotyping in autopolyploid species? I.e. each WGS sample may have up to four different alleles within a particular locus.

Regards,
Denis

**Comment by Arkarachai** [comment]
Hi Denis,
The profiling part should work since it's just count of length for all STR mapped to that location. However, the genotyping part would assume diplod, so it won't be useful to run that part. 
I'm not aware if there is any tool for STR that is modeled on polyploid, so this might be your best bet.

**Comment by DenisGoryunov** [comment]
Hi Arkarachai,

Thank you for your response.

In the STR-FM paper was noted:
"Finally, STR-FM runs a profiler tool, which groups all reads with STRs
that are mapped to the same location in the reference genome. As a result,
an array of all STR lengths from the reads mapping to a particular
STR-containing locus is generated."
Could you advise me please, where can i find a short example of such a
table, to decide if it would be useful for my pipeline?

In addition, i'd like to ask, if i can use a FASTA file with multiple
targeted regions as input for the SSR profiling instead of the complete
genome sequence?

Regards,
Denis

пн, 27 сент. 2021 г. в 20:53, Arkarachai Fungtammasan <
***@***.***>:

**Comment by Arkarachai** [comment]
HI Denis,
The test-data folder contains input and output for each script in the pipeline, so you can check if the output format has the information you need.
The tools are available on Galaxy main, so you can do the small test (it's free) before you invest in setting up for your cluster. To be fair, I haven't further developed this tool since 2015. There might be a better option out there. It's hard to know. Most tools are specialized for human. 
I guess STR profiling in FASTA could be thought of as very fragment genome sequence. The output is just the position and length of STR in FASTA.

**Comment by DenisGoryunov** [comment]
Hi Arkarachai,

Thank you very much for the detailed reply and explanations. I appreciate
your help.

Regards,
Denis

вт, 28 сент. 2021 г. в 20:38, Arkarachai Fungtammasan <
***@***.***>:
